name: Python App with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4  # Change this to the Python version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask==2.0.1  # Specify the desired Flask version

    - name: Build Docker image
      run: docker build -t snake_game -f Dockerfile .

    - name: Login to Docker Hub with Access Token
      run: |
        echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image to Docker Hub
      if: github.event_name == 'push'  # Optional: Only push on push events
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/snake_game:latest

    - name: Run tests
      run: |
        pip install pytest
        pytest

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results
